### PR TITLE
Livy Bootstrap Action Creation

### PR DESCRIPTION
**Pull request by ericjeffers-ifactor**
Bootstrap action created for installing [livy](http://livy.io/) server on the master node of an EMR cluster. 

This was created to allow ease of integrating with a long-running EMR cluster in which spark jobs need to be run concurrently. 

Upon start up, the livy server can be reached at port 8998.

### CODE REVIEW

**Comment by apetresc** [comment]
@awslabs Any reason there's been no feedback on this PR? It seems very useful, and the contribution itself seems high-quality.

**Comment by synhershko** [comment]
+1

**Comment by johnkabler** [comment]
@ericjeffers-ifactor  Thanks for doing this.  I'll just go to your repo since the AWS folks don't seem to have noticed this.

**Comment by chriskite** [comment]
+1

**Comment by Westermann** [comment]
+1

**Comment by apetresc** [comment]
Well, the latest version of the EMR release (5.9.0) now bundles Livy as an application, so presumably there's no more need to install it through a bootstrap action anymore.

**Comment by ericjeffers-ifactor** [comment]
@apetresc - Yeah I saw this news last month https://aws.amazon.com/about-aws/whats-new/2017/10/support-for-apache-livy-hue-4-0-1-and-presto-0-184-on-amazon-emr-release-5-9-0/ 

Going to close this PR since it's no longer needed.

**Pull request closed without merging**
