### PR TITLE
Added ability to provide custom jars to spark classpath

### PR DESCRIPTION
**Pull request by aniketbhatnagar**

### CODE REVIEW

**Comment by christopherbozeman** [comment]
I like it!  Thanks

**Comment by nieldomingo** [comment]
i really need this. pls merge.

**Comment by christopherbozeman** [comment]
This is a great idea, take a look at https://github.com/christopherbozeman/emr-bootstrap-actions/commits/20150114-aniketbhatnagar forhow I iterated on it.   Basically, I moved the user-provided jars action all to install-spark script so build script does not need to be adjusted.  Also added the feature "-a" to bump spark-assembly-*.jar to the front of the spark classpath.

**Comment by stmcpherson** [comment]
This was covered by Christopher's patch in Pull Request #40

**Comment by aniketbhatnagar** [comment]
Thanks everyone :)

**Pull request closed without merging**
