### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by mwallman**
Bootstrap actions that support for both EMR 3.X and 4.X.

### CODE REVIEW

**Comment by stmcpherson** [comment]
Thanks for the PR. Can you consolidate Saltstack and Syslog folders into one?

**Comment by mwallman** [comment]
Suggestion on the naming? They do quite different things.

**Comment by mwallman** [comment]
Maybe sysops?

**Comment by stmcpherson** [comment]
On second thought it may be fine that they are in separate folders.  

Can you rename the .md files to be readme.md. This will help them show in Github console on the welcome page for their respective folders.

**Comment by mwallman** [comment]
Good catch! Names updated, and readme's look good...

**Pull request merged**
