### PR TITLE
Create install_java_8.sh

### PR DESCRIPTION
**Pull request by juskrey**
Install java 8 on AMI with Amazon Linux

### CODE REVIEW

**Comment by stmcpherson** [comment]
Sorry for the delay in merging these. Can you add a readme for the bootstrap. Also, We'd prefer that you use openJDK. For example look at the install of OpenJDK on https://github.com/mombergm/emr-bootstrap-actions/blob/master/presto-095/install-presto

**Comment by stmcpherson** [comment]
Can you use sudo "yum install java-1.8.0-openjdk-headless.x86_64 -y"  instead of the dedicated install_java_8.sh?

**Comment by juskrey** [comment]
Sorry for delay,
Indeed @stmcpherson ! Now this is a viable option, still alternatives and some vars have to be set after that.
I'll test that and rerequest later.

**Comment by pmvilaca** [comment]
I'm trying to use EMR with Spark 1.5.0 but I need to use Java 8, so I was searching for a bootstrap script to do that and apparently there is no official script for that. Can't we provide that script on this repo, as it seems to be a normal requirement for people that is using spark?

**Pull request closed without merging**
